cask_args appdir: '/Applications'
tap 'caskroom/cask'

brew 'imagemagick'
brew 'zsh'

cask 'sublime-text'
cask '1password'
cask 'google-chrome'
cask 'alfred'
cask 'dropbox'
cask 'handbrake'
cask 'firefox'
cask 'mou'
cask 'kaleidoscope'
cask 'sequel-pro'
cask 'skype'
cask 'sonos'
cask 'spotify'
cask 'things'
cask 'tower'
cask 'transmit'
cask 'unrarx'
cask 'panic-unison'
cask 'vlc'
cask 'iterm2'
cask 'istat-menus'
cask 'ynab'
cask 'ios-console'
cask 'appcode'
cask 'arq'
cask 'charles'
cask 'coderunner'
cask 'dash'
cask 'gpgtools'
cask 'mamp'
cask 'omnioutliner'
cask 'parallels-desktop'
cask 'paw'
cask 'screenhero'
cask 'simpholders'
cask 'slack'
cask 'soulver'
cask 'steam'
cask 'teamviewer'
cask 'utorrent'

mas 'outBank', id: 775678532

#cask 'seafile-client'

#cask 'microsoft-office'